-- Add local_id (client UUID) to recipes and ingredients for offline-first sync
ALTER TABLE recipes ADD COLUMN local_id VARCHAR(255) UNIQUE;
ALTER TABLE ingredients ADD COLUMN local_id VARCHAR(255) UNIQUE;

-- Backfill existing rows with generated UUIDs
UPDATE recipes SET local_id = gen_random_uuid()::text WHERE local_id IS NULL;
UPDATE ingredients SET local_id = gen_random_uuid()::text WHERE local_id IS NULL;

ALTER TABLE recipes ALTER COLUMN local_id SET NOT NULL;
ALTER TABLE ingredients ALTER COLUMN local_id SET NOT NULL;

-- Units table for measurement types
CREATE TABLE IF NOT EXISTS units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    symbol VARCHAR(50) NOT NULL,
    measurement_type VARCHAR(50) NOT NULL CHECK (measurement_type IN ('WEIGHT', 'VOLUME', 'COUNT')),
    base_conversion_factor DOUBLE PRECISION NOT NULL
);

-- Quantities table for measured amounts
CREATE TABLE IF NOT EXISTS quantities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id VARCHAR(255) UNIQUE NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    unit_id BIGINT NOT NULL REFERENCES units(id)
);

-- Add quantity support to recipe-ingredient relationships
ALTER TABLE recipe_ingredients ADD COLUMN quantity_id BIGINT REFERENCES quantities(id);
